name: LargierJ build

on:
  push:
    branches:
      - feature/*
      - release/*
  workflow_dispatch:
    inputs:
      deploySecret:
        description: 'Deploy secret for deploy to remote server'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Deploy secret is $DEPLOY_SECRET"
        env:
          DEPLOY_SECRET: ${{ inputs.deploySecret }}
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        env:
          CI: false
        run: |
          mvn -B package --file pom.xml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if:
    steps:
      - name: Publish
        uses: nogsantos/scp-deploy@master
        if: contains(github.ref, 'refs/heads/release')
        with:
          src: ./largier-server/target/largier-run.jar
          host: ${{ secrets.DEPLOY_HOST }}
          remote: ${{ secrets.DEPLOY_DIR }}
          port: ${{ secrets.DEPLOY_PORT }}
          user: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
